const wordsList = {
    "3/14": [
        { english: "counterfeit", chinese: "偽造", partOfSpeech: "verb/adjective", synonyms: ["forge", "fake"] },
        { english: "enquire", chinese: "詢問", partOfSpeech: "verb", synonyms: ["inquire", "ask"] },
        { english: "dedicate", chinese: "奉獻", partOfSpeech: "verb", synonyms: ["devote", "commit"] },
        { english: "committed", chinese: "致力於", partOfSpeech: "adjective", synonyms: ["devoted", "dedicated"] },
        { english: "mentor", chinese: "導師", partOfSpeech: "noun/verb", synonyms: ["guide", "coach"] },
        { english: "crucial", chinese: "關鍵的", partOfSpeech: "adjective", synonyms: ["essential", "vital"] },
        { english: "assist", chinese: "協助", partOfSpeech: "verb", synonyms: ["help", "aid"] },
        { english: "peer", chinese: "同伴", partOfSpeech: "noun", synonyms: ["companion", "colleague"] },
        { english: "inform", chinese: "通知", partOfSpeech: "verb", synonyms: ["notify", "tell"] },
        { english: "conform", chinese: "符合", partOfSpeech: "verb", synonyms: ["comply", "adapt"] },
        { english: "material", chinese: "材料", partOfSpeech: "noun", synonyms: ["substance", "stuff"] },
        { english: "adhere", chinese: "堅持", partOfSpeech: "verb", synonyms: ["stick to", "follow"] },
        { english: "beckon", chinese: "招手", partOfSpeech: "verb", synonyms: ["gesture", "wave"] },
        { english: "interior", chinese: "內部", partOfSpeech: "noun/adjective", synonyms: ["inside", "internal"] },
        { english: "statement", chinese: "陳述", partOfSpeech: "noun", synonyms: ["declaration", "remark"] },
        { english: "backing", chinese: "支持", partOfSpeech: "noun", synonyms: ["support", "endorsement"] },
        { english: "hardly", chinese: "幾乎不", partOfSpeech: "adverb", synonyms: ["barely", "scarcely"] },
        { english: "nearly", chinese: "幾乎", partOfSpeech: "adverb", synonyms: ["almost", "approximately"] },
        { english: "merely", chinese: "僅僅", partOfSpeech: "adverb", synonyms: ["just", "only"] },
        { english: "barely", chinese: "勉強", partOfSpeech: "adverb", synonyms: ["hardly", "scarcely"] },
        { english: "regain", chinese: "恢復", partOfSpeech: "verb", synonyms: ["recover", "retrieve"] },
        { english: "underwent", chinese: "經歷", partOfSpeech: "verb", synonyms: ["experienced", "endured"] },
        { english: "renovation", chinese: "翻新", partOfSpeech: "noun", synonyms: ["remodeling", "restoration"] },
        { english: "audit", chinese: "審計", partOfSpeech: "noun/verb", synonyms: ["review", "inspect"] },
        { english: "dispose", chinese: "處理", partOfSpeech: "verb", synonyms: ["discard", "get rid of"] },
        { english: "tenancy", chinese: "租賃", partOfSpeech: "noun", synonyms: ["lease", "occupancy"] },
        { english: "premise", chinese: "前提", partOfSpeech: "noun", synonyms: ["assumption", "basis"] },
        { english: "commitment", chinese: "承諾", partOfSpeech: "noun", synonyms: ["promise", "dedication"] },
        { english: "obliged", chinese: "有義務的", partOfSpeech: "adjective", synonyms: ["required", "compelled"] },
        { english: "plunged", chinese: "猛跌", partOfSpeech: "verb", synonyms: ["dropped", "fell"] },
        { english: "demand", chinese: "需求", partOfSpeech: "noun/verb", synonyms: ["require", "request"] },
        { english: "exclusion", chinese: "排除", partOfSpeech: "noun", synonyms: ["omission", "rejection"] },
        { english: "instability", chinese: "不穩定", partOfSpeech: "noun", synonyms: ["uncertainty", "volatility"] },
        { english: "evolve", chinese: "進化", partOfSpeech: "verb", synonyms: ["develop", "progress"] },
        { english: "involve", chinese: "涉及", partOfSpeech: "verb", synonyms: ["include", "entail"] },
        { english: "invoke", chinese: "調用", partOfSpeech: "verb", synonyms: ["call upon", "summon"] },
        { english: "conscious", chinese: "有意識的", partOfSpeech: "adjective", synonyms: ["aware", "mindful"] },
        { english: "cozy", chinese: "舒適的", partOfSpeech: "adjective", synonyms: ["comfortable", "snug"] },
        { english: "exotic", chinese: "異國的", partOfSpeech: "adjective", synonyms: ["foreign", "unusual"] },
        { english: "receptive", chinese: "接受的", partOfSpeech: "adjective", synonyms: ["open", "responsive"] },
        { english: "decline", chinese: "衰退", partOfSpeech: "verb/noun", synonyms: ["decrease", "refuse"] },
        { english: "discretion", chinese: "審慎", partOfSpeech: "noun", synonyms: ["judgment", "prudence"] },
        { english: "subjective", chinese: "主觀的", partOfSpeech: "adjective", synonyms: ["personal", "biased"] },
        { english: "objective", chinese: "客觀的", partOfSpeech: "adjective", synonyms: ["impartial", "unbiased"] },
        { english: "hinder", chinese: "阻礙", partOfSpeech: "verb", synonyms: ["obstruct", "impede"] },
        { english: "on account of", chinese: "由於", partOfSpeech: "preposition", synonyms: ["because of", "due to"] },
        { english: "conduct", chinese: "行為", partOfSpeech: "noun/verb", synonyms: ["behavior", "manage"] },
        { english: "subordinate", chinese: "下屬", partOfSpeech: "noun/adjective", synonyms: ["junior", "inferior"] },
        { english: "overlapped", chinese: "重疊", partOfSpeech: "verb", synonyms: ["coincided", "intersected"] },
        { english: "marginalized", chinese: "邊緣化", partOfSpeech: "adjective", synonyms: ["excluded", "sidelined"] },
        { english: "exaggerated", chinese: "誇張的", partOfSpeech: "adjective", synonyms: ["overstated", "inflated"] },
        { english: "vanquished", chinese: "被征服的", partOfSpeech: "verb/adjective", synonyms: ["defeated", "conquered"] },
        { english: "regardless of", chinese: "不管", partOfSpeech: "preposition", synonyms: ["despite", "irrespective of"] },
        { english: "punctually", chinese: "準時地", partOfSpeech: "adverb", synonyms: ["promptly", "on time"] },
        { english: "with respect to", chinese: "關於", partOfSpeech: "preposition", synonyms: ["regarding", "concerning"] },
    ],
    "3/15": [
        { english: "disrupted", chinese: "中斷的", partOfSpeech: "adjective", synonyms: ["interrupted", "disturbed"] },
        { english: "subdued", chinese: "被壓制的", partOfSpeech: "adjective", synonyms: ["restrained", "suppressed"] },
        { english: "overturned", chinese: "推翻", partOfSpeech: "verb", synonyms: ["reversed", "invalidated"] },
        { english: "adjusted", chinese: "調整的", partOfSpeech: "adjective", synonyms: ["modified", "adapted"] },
        { english: "disciplinary", chinese: "紀律的", partOfSpeech: "adjective", synonyms: ["corrective", "punitive"] },
        { english: "pessimistic", chinese: "悲觀的", partOfSpeech: "adjective", synonyms: ["negative", "gloomy"] },
        { english: "outlook", chinese: "展望", partOfSpeech: "noun", synonyms: ["perspective", "forecast"] },
        { english: "recession", chinese: "衰退", partOfSpeech: "noun", synonyms: ["downturn", "decline"] },
        { english: "expand", chinese: "擴張", partOfSpeech: "verb", synonyms: ["grow", "increase"] },
        { english: "downsize", chinese: "縮減", partOfSpeech: "verb", synonyms: ["reduce", "cut back"] },
        { english: "fluctuate", chinese: "波動", partOfSpeech: "verb", synonyms: ["vary", "oscillate"] },
        { english: "deteriorate", chinese: "惡化", partOfSpeech: "verb", synonyms: ["worsen", "decline"] },
        { english: "cutting-edge", chinese: "尖端的", partOfSpeech: "adjective", synonyms: ["innovative", "advanced"] },
        { english: "outsourced", chinese: "外包的", partOfSpeech: "adjective", synonyms: ["contracted", "delegated"] },
        { english: "comprehensively", chinese: "全面地", partOfSpeech: "adverb", synonyms: ["thoroughly", "completely"] },
        { english: "commission", chinese: "委託", partOfSpeech: "noun/verb", synonyms: ["assignment", "authorize"] },
        { english: "eminent", chinese: "傑出的", partOfSpeech: "adjective", synonyms: ["distinguished", "prominent"] },
        { english: "imminent", chinese: "即將來臨的", partOfSpeech: "adjective", synonyms: ["impending", "approaching"] },
        { english: "inherent", chinese: "固有的", partOfSpeech: "adjective", synonyms: ["intrinsic", "natural"] },
        { english: "bond", chinese: "債券", partOfSpeech: "noun", synonyms: ["connection", "link"] },
        { english: "grant", chinese: "授予", partOfSpeech: "verb/noun", synonyms: ["award", "give"] },
        { english: "stake", chinese: "股份", partOfSpeech: "noun", synonyms: ["share", "interest"] },
        { english: "delegate", chinese: "委派", partOfSpeech: "verb/noun", synonyms: ["assign", "representative"] },
        { english: "denounce", chinese: "譴責", partOfSpeech: "verb", synonyms: ["condemn", "criticize"] },
        { english: "deprive", chinese: "剝奪", partOfSpeech: "verb", synonyms: ["deny", "withhold"] },
        { english: "progression", chinese: "進展", partOfSpeech: "noun", synonyms: ["advancement", "development"] },
        { english: "comprise", chinese: "包含", partOfSpeech: "verb", synonyms: ["consist of", "include"] },
        { english: "underdeveloped", chinese: "未開發的", partOfSpeech: "adjective", synonyms: ["developing", "backward"] },
        { english: "undertaking", chinese: "事業", partOfSpeech: "noun", synonyms: ["project", "venture"] },
        { english: "venture", chinese: "冒險", partOfSpeech: "noun/verb", synonyms: ["enterprise", "risk"] },
        { english: "synonymous", chinese: "同義的", partOfSpeech: "adjective", synonyms: ["identical", "equivalent"] },
        { english: "anonymous", chinese: "匿名的", partOfSpeech: "adjective", synonyms: ["unnamed", "unknown"] },
        { english: "unanimous", chinese: "一致的", partOfSpeech: "adjective", synonyms: ["agreed", "harmonious"] },
        { english: "infamous", chinese: "惡名昭彰的", partOfSpeech: "adjective", synonyms: ["notorious", "scandalous"] },
        { english: "consent", chinese: "同意", partOfSpeech: "noun/verb", synonyms: ["approval", "permission"] },
        { english: "residence", chinese: "住所", partOfSpeech: "noun", synonyms: ["home", "dwelling"] },
        { english: "venue", chinese: "場地", partOfSpeech: "noun", synonyms: ["location", "site"] },
        { english: "issue", chinese: "問題", partOfSpeech: "noun/verb", synonyms: ["problem", "matter"] },
        { english: "insist", chinese: "堅持", partOfSpeech: "verb", synonyms: ["persist", "demand"] },
        { english: "ingredient", chinese: "成分", partOfSpeech: "noun", synonyms: ["component", "element"] },
        { english: "narrow", chinese: "狹窄的", partOfSpeech: "adjective/verb", synonyms: ["slim", "confined"] },
        { english: "strengthen", chinese: "加強", partOfSpeech: "verb", synonyms: ["reinforce", "fortify"] },
        { english: "widening", chinese: "擴大的", partOfSpeech: "adjective", synonyms: ["expanding", "broadening"] },
        { english: "gradually", chinese: "逐漸地", partOfSpeech: "adverb", synonyms: ["slowly", "progressively"] },
        { english: "trustee", chinese: "受託人", partOfSpeech: "noun", synonyms: ["guardian", "custodian"] }
    ],
};

export default wordsList;